name: Queue

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - 'master'
            
jobs:
  check:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git
          git clone https://github.com/google/googletest
          cd googletest && mkdir build
          cd build && cmake .. && make
          sudo make install
      - name: Build and Run
        run: |
          make
          make check
 